'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout } from 'antd';
import SideBarItems from '@/ui/Components/Layout/SideBarItems';
import PageHeader from '@/ui/Components/Layout/PageHeader';
import Order from './content/Order';
import SidebarProvider from '@/context/SidebarProvider';
// import { Layout } from 'antd';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <SidebarProvider>
            <Layout>
              <SideBarItems />
              <Layout>
                <PageHeader />
                {children}
              </Layout>
            </Layout>
          </SidebarProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
